language: python

python:
  - "3.7"

addons:
  apt:
    packages:
      - gfortran

install:
  - pip install black coverage coveralls

script:
  - python -m coverage run -m unittest discover
  - black --check --skip-string-normalization .

after_success:
  - coveralls

notifications:
  email:
    - d.mentiplay@gmail.com
