language: python

python:
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - gfortran

install:
  - pip install black click coverage coveralls isort jinja2 mypy pytest tomlkit

script:
  - python -m coverage run -m pytest
  - python -m isort --check-only .
  - python -m black --check --skip-string-normalization .
  - python -m mypy --ignore-missing-imports phantombuild tests

after_success:
  - python -m coveralls

notifications:
  email:
    recipients:
      - d.mentiplay@gmail.com
    on_success: change
    on_failure: always
