language: python

python:
  - "3.7"

addons:
  apt:
    packages:
      - gfortran

install:
  - pip install black click coverage coveralls isort jinja2 mypy pytest tomlkit

script:
  - python -m coverage run -m pytest
  - isort --check-only -rc
  - black --check --skip-string-normalization .
  - mypy --ignore-missing-imports phantombuild tests

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - d.mentiplay@gmail.com
    on_success: change
    on_failure: always
